# Generated by Django 5.0 on 2024-01-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_user_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
